version: '3'

#Se define la red interna a ser utilizada
networks:
    stp_net:
        driver: bridge
        ipam:
          driver: default
          config:
            - subnet: 172.19.0.0/24

services:
    db:
        build: files/pgalpine
        image: stp/pg
        expose:
            - "5432"
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=test
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=stp123
        networks:
            stp_net:
              ipv4_address: 172.19.0.2
    cache:
        build: files/memcached
        image: stp/memcached
        expose:
            - "11211"
        ports:
            - "11211:11211"
        networks:
            stp_net:
              ipv4_address: 172.19.0.3
    backend:
        build: files/tomcat
        image: stp/tomcat
        expose:
            - "8080"
            - "8000"
            - "8009"
            - "8443"
        ports:
            - "8080:8080"
            - "8000:8000"
            - "8009:8009"
            - "8443:8443"
        volumes:
            - ./files/cas/etc/cas:/etc/cas
            - ./repos/webapps:/opt/tomcat/webapps
        networks:
            stp_net:
              ipv4_address: 172.19.0.4
        extra_hosts:
            - "app03.stp.gov.py:172.19.0.3"
            - "spr.stp.gov.py:172.19.0.5"
            - "login.stp.gov.py:172.19.0.5"
            - "pg01:172.19.0.2"
            - "pg01.stp.gov.py:172.19.0.2"
    frontend:
        build: files/nginx
        image: stp/nginx
        expose:
            - "80"
            - "443"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./files/www:/var/www/html
        networks:
            stp_net:
              ipv4_address: 172.19.0.5
